const searchSources = {
  'Gamer': [
    'teclado gamer',
    'mouse gamer',
    'headset gamer',
    'monitor gamer',
    'cadeira gamer',
    'setup gamer',
    'mousepad gamer grande'
  ],
  'Cozinha': [
    'air fryer',
    'jogo de panelas',
    'cafeteira',
    'liquidificador',
    'batedeira planetária',
    'faca de cozinha',
    'frigideira antiaderente',
    'panela pressão',
    'micro-ondas',
    'chaleira elétrica',
    'espresso máquina café',
    'processador de alimentos',
    'sanduicheira grill elétrico',
    'pote hermético organização',
    'escorredor de macarrão',
    'tábua de corte',
    'forma bolo',
    'torradeira',
    'kit utensílios cozinha'
  ],
  'Eletrônicos': [
    'fone bluetooth',
    'smartwatch',
    'notebook',
    'ar condicionado',
    'máquina de lavar',
    'tv smart',
    'alexa echo dot'
  ],
  'Beleza feminina': [
    'maquiagem',
    'skincare',
    'perfume feminino',
    'secador de cabelo',
    'chapinha',
    'escova rotativa',
    'kit manicure',
    'hidratante facial',
    'protetor solar facial'
  ],
  'Pet': [
    'ração cachorro',
    'ração gato',
    'petisco cachorro',
    'petisco gato',
    'brinquedo pet',
    'arranhador gato',
    'cama pet',
    'casinha cachorro',
    'coleira cachorro',
    'guia pet',
    'comedouro automático',
    'fonte água pet',
    'tapete higiênico',
    'shampoo pet',
    'perfume pet',
    'antipulgas',
    'caixa transporte pet',
    'mochila pet',
    'roupa cachorro',
    'acessórios pet'
  ],
  'Leitura': [
    'kindle',
    'livros',
    'box livros',
    'romance',
    'fantasia',
    'ficção científica',
    'desenvolvimento pessoal',
    'negócios',
    'produtividade',
    'psicologia',
    'mangá',
    'quadrinhos',
    'livros infantis',
    'suspense',
    'terror',
    'biografias',
    'literatura clássica',
    'e-reader',
    'luminária leitura',
    'suporte livro'
  ],
  'Academia_Fitness': [
    'whey protein',
    'creatina',
    'pré treino',
    'coqueteleira',
    'corda pular',
    'halteres',
    'elástico treino',
    'kit academia',
    'luva musculação',
    'straps',
    'faixa resistência',
    'colchonete',
    'smartband fitness',
    'roupa academia',
    'legging fitness',
    'top fitness',
    'garrafa térmica fitness',
    'massageador muscular',
    'balança corporal',
    'acessórios treino'
  ],
  'Mobile_Games': [
    'iphone',
    'samsung galaxy',
    'xiaomi redmi',
    'motorola moto',
    'smartphone 5g',
    'ps5',
    'playstation 5',
    'ps4',
    'xbox series x',
    'xbox series s',
    'nintendo switch',
    'steam deck',
    'controle ps5',
    'controle xbox',
    'controle nintendo switch'
  ]
};

module.exports = searchSources;
